name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter 3.44.1
        shell: pwsh
        run: |
          git clone https://github.com/flutter/flutter.git C:\flutter
          cd C:\flutter
          git fetch --tags
          git checkout tags/3.44.1
          $env:Path = "C:\flutter\bin;$env:Path"
          echo "PATH=$env:Path" >> $env:GITHUB_ENV

      - name: Where is Flutter?
        shell: pwsh
        run: |
          where.exe flutter
          Get-Command flutter
          C:\flutter\bin\flutter.bat --version

      - name: Flutter Info
        shell: pwsh
        run: |
          C:\flutter\bin\flutter.bat --version
          C:\flutter\bin\dart.bat --version

      - name: Enable Windows
        run: C:\flutter\bin\flutter.bat config --enable-windows-desktop

      - name: Clean
        run: C:\flutter\bin\flutter.bat clean

      - name: Get Dependencies
        run: C:\flutter\bin\flutter.bat pub get

      - name: Generate Code
        run: C:\flutter\bin\dart.bat run build_runner build --delete-conflicting-outputs

      - name: Build
        run: C:\flutter\bin\flutter.bat build windows --release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: tezgah_pos_windows
          path: build/windows/x64/runner/Release