name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show pubspec
        shell: pwsh
        run: |
          Write-Host "===== COMMIT ====="
          git rev-parse HEAD

          Write-Host "===== NETWORK INFO ====="
          Select-String -Path pubspec.yaml -Pattern "network_info_plus"

          Write-Host "===== SHARE PLUS ====="
          Select-String -Path pubspec.yaml -Pattern "share_plus"

          Write-Host "===== PRINT BT ====="
          Select-String -Path pubspec.yaml -Pattern "print_bluetooth_thermal"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.1"
          channel: stable
          cache: false

      - name: Flutter Info
        run: |
          flutter --version
          dart --version

      - run: flutter config --enable-windows-desktop

      - run: flutter clean

      - run: flutter pub get

      - run: flutter build windows --release

      - uses: actions/upload-artifact@v4
        with:
          name: tezgah_pos_windows
          path: build/windows/x64/runner/Release